### PR TITLE
Removed MultiMap AddEntryListener method

### PR DESCRIPTION
**Pull request by yuce**

### CODE REVIEW

**Review by utku-caglayan — APPROVED** [review]
Looks good!

**Comment by srknzl** [comment]
Any justification?

**Comment by yuce** [comment]
@srknzl We're changing the listener API for Map and MultiMap as you know. We'll rework `AddEntryListener` for MultiMap and add it back in v1.3.0

**Comment by yuce** [comment]
MultiMap is slated to be released in v1.2.0, so there is no concern about backward compatibility.

**Review by srknzl — APPROVED** [review]

**Pull request merged**
