### PR TITLE
remove chaining from configs

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
This pr removes chaining from configs

This pr fixes a typo in samples as well.

### CODE REVIEW

**Comment by mustafaiman** [comment]
I don't think it is very common in Golang to use method chaining. Specifically because, methods sometimes return error and you cannot handle that error happened int the middle of the method chain. I suggest keeping chaining out of this codebase as much as possible.

**Comment by mustafaiman** [comment]
@sancar wdyt? 🔼

**Comment by sancar** [comment]
Personally, I see no harm to use chaining where possible. The config methods that needs to return error is relatively low.

**Comment by SaitTalhaNisanci** [comment]
Chaining is not idiomatic in go since methods return errors in general, but as @sancar said in our case it is only a few methods. https://stackoverflow.com/questions/27297702/go-method-chaining-and-error-handling


How should we proceed with this ? @sancar  @mustafaiman

**Comment by sancar** [comment]
We can drop chaining for go. I am OK with this.

**Comment by SaitTalhaNisanci** [comment]
Okay I will drop chaining from existing methods in this PR then.

**Pull request merged**
