### PR TITLE
Implemented RawData & Added several tests

### PR DESCRIPTION
**Pull request by gulcesirvanci**
-Implemented RawData.
-Added tests: RawData, RawDataWithoutRegistering,  RawDataInvalidWrite, RawDataInvalidRead.
-Implemented EmptyObjectDataOutput.

### CODE REVIEW

**Comment by gulcesirvanci** [comment]
verify

**Comment by gulcesirvanci** [comment]
verify

**Comment by gulcesirvanci** [comment]
verify

**Comment by yuce** [comment]
Closed in favor of: https://github.com/hazelcast/hazelcast-go-client/pull/666

**Pull request closed without merging**
