### PR TITLE
Add docs badge to readme

### PR DESCRIPTION
**Pull request by utku-caglayan**
Adds following documentation badge shortcut to readme
[Go Reference](https://pkg.go.dev/github.com/hazelcast/hazelcast-go-client)

### CODE REVIEW

**Review by yuce — APPROVED** [review]
Nice idea!

**Review by nevzatseferoglu — APPROVED** [review]
If you want, we can add more badges such as; `coverage`, `version`, `dependencies` etc. I suppose that there is no privacy concern on these information.

**Comment by utku-caglayan** [comment]
> If you want, we can add more badges such as; `coverage`, `version`, `dependencies` etc. I suppose that there is no privacy concern on these informations.

Sounds good, if you have seen any, can you share one as an example?

**Comment by yuce** [comment]
Let's merge this PR and discuss about other badges later.

**Pull request merged**
