### PR TITLE
calculate coverage correctly

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**

### CODE REVIEW

**Comment by SaitTalhaNisanci** [comment]
verify

**Comment by SaitTalhaNisanci** [comment]
verify

**Comment by SaitTalhaNisanci** [comment]
verify

**Comment by SaitTalhaNisanci** [comment]
verify

**Comment by SaitTalhaNisanci** [comment]
verify

**Comment by sancar** [comment]
verify

**Pull request merged**
