### PR TITLE
Skip line after func

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Comment by furkansenharputlu** [comment]
Verify

**Comment by furkansenharputlu** [comment]
verify

**Comment by sancar** [comment]
Can we check this via an automated tool  ? Does gofmt etc has an option to enforce this ?

**Comment by SaitTalhaNisanci** [comment]
https://github.com/golang/go/issues/22337

**Comment by furkansenharputlu** [comment]
I don’t know. I used regex.

**Comment by mustafaiman** [comment]
there is [golint](https://github.com/golang/lint). I suggest integrating golint into build pipeline and fail the prs whenever golint complains.

**Pull request merged**
